name = "GridapODEs"
uuid = "55e38337-5b6e-4c7c-9cfc-e00dd49102e6"
authors = ["Santiago Badia"]
version = "0.1.0"

[deps]
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
Gridap = "56d4f2e9-7ea1-5844-9cf6-b9c51ca7ce8e"
LineSearches = "d3d80556-e9d4-5f37-9878-2ab0fcc64255"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]

[compat]
ForwardDiff = "0.10.10"
Gridap = "0.9.0"
LineSearches = "7.0.1"
julia = "1.0.5"
